language: python
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database stoic_test;' -U postgres
python:
  - "3.5"
cache: pip
install:
  - "pip install -r dev-requirements.txt"
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script: 
  - py.test --pep8 users
  - py.test -v --cov=users --cov-report term-missing --pep8 test
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t kolbman.xyz:3333/users .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://kolbman.xyz:3333;
    docker push kolbman.xyz:3333/users;
    fi
